/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.19
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON

#include "Python.h"

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#                       define SWIGIMPORT(a) extern a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#                       define SWIGIMPORT(a) extern a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#                       define SWIGIMPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#                       define SWIGIMPORT(a) a
#               endif
#       endif
#else
#       define SWIGEXPORT(a) a
#       define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;                 
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;	
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(const char *)     SWIG_TypeName(const swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);

#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      if (tc->clientdata) ti->clientdata = tc->clientdata;	
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;  /**/
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;  /**/
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) 
{
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
     ty = (*ty->dcast)(ptr);
     if (ty) lastty = ty;
  }
  return lastty;
}

/* Return the name associated with this type */
SWIGRUNTIME(const char *)
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata == clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
	if ((strcmp(tc->name, equiv->name) == 0))
	  SWIG_TypeClientData(tc,clientdata);
	tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}
#endif

#ifdef __cplusplus
}

#endif

/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Flags for pointer conversion */

#define SWIG_POINTER_EXCEPTION     0x1
#define SWIG_POINTER_DISOWN        0x2

/* Exception handling in wrappers */
#define SWIG_fail   goto fail

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink(void);
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGEXPORT(int)               SWIG_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGEXPORT(char *)            SWIG_PackData(char *c, void *, int);
SWIGEXPORT(char *)            SWIG_UnpackData(char *c, void *, int);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, swig_type_info *,int own);
SWIGEXPORT(PyObject *)        SWIG_NewPackedObj(void *, int sz, swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, swig_const_info constants[]);
#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;
  int    newref = 0;
  PyObject  *pyobj = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  }  
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) { Py_DECREF(obj); }
      return 0;
    } else {
      if (newref) { Py_DECREF(obj); }
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) { Py_DECREF(obj); }
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }

  if ((pyobj) && (flags & SWIG_POINTER_DISOWN)) {
      PyObject *zero = PyInt_FromLong(0);
      PyObject_SetAttrString(pyobj,(char*)"thisown",zero);
      Py_DECREF(zero);
  }
  return 0;

type_error:
  if (flags & SWIG_POINTER_EXCEPTION) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[1024];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (inst) {
      if (own) {
	PyObject *n = PyInt_FromLong(1);
	PyObject_SetAttrString(inst,(char*)"thisown",n);
	Py_DECREF(n);
      }
      robj = inst;
    }
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif








/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_eth_handle swig_types[0] 
#define  SWIGTYPE_p_ip_handle swig_types[1] 
#define  SWIGTYPE_p_arp_handle swig_types[2] 
#define  SWIGTYPE_p_rand_handle swig_types[3] 
#define  SWIGTYPE_p_route_handle swig_types[4] 
#define  SWIGTYPE_p_p_char swig_types[5] 
#define  SWIGTYPE_p_addr_iter swig_types[6] 
#define  SWIGTYPE_p_addr swig_types[7] 
#define  SWIGTYPE_p_int swig_types[8] 
static swig_type_info *swig_types[10];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= _dnet.so
  ------------------------------------------------*/
#define SWIG_init    init_dnet

#define SWIG_name    "_dnet"

#include <sys/types.h>
#include <dnet.h>
#include <errno.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>


#define  SWIG_MemoryError    1
#define  SWIG_IOError        2
#define  SWIG_RuntimeError   3
#define  SWIG_IndexError     4
#define  SWIG_TypeError      5
#define  SWIG_DivisionByZero 6
#define  SWIG_OverflowError  7
#define  SWIG_SyntaxError    8
#define  SWIG_ValueError     9
#define  SWIG_SystemError   10
#define  SWIG_UnknownError  99


static void _SWIG_exception(int code, const char *msg) {
  switch(code) {
  case SWIG_MemoryError:
    PyErr_SetString(PyExc_MemoryError,msg);
    break;
  case SWIG_IOError:
    PyErr_SetString(PyExc_IOError,msg);
    break;
  case SWIG_RuntimeError:
    PyErr_SetString(PyExc_RuntimeError,msg);
    break;
  case SWIG_IndexError:
    PyErr_SetString(PyExc_IndexError,msg);
    break;
  case SWIG_TypeError:
    PyErr_SetString(PyExc_TypeError,msg);
    break;
  case SWIG_DivisionByZero:
    PyErr_SetString(PyExc_ZeroDivisionError,msg);
    break;
  case SWIG_OverflowError:
    PyErr_SetString(PyExc_OverflowError,msg);
    break;
  case SWIG_SyntaxError:
    PyErr_SetString(PyExc_SyntaxError,msg);
    break;
  case SWIG_ValueError:
    PyErr_SetString(PyExc_ValueError,msg);
    break;
  case SWIG_SystemError:
    PyErr_SetString(PyExc_SystemError,msg);
    break;
  default:
    PyErr_SetString(PyExc_RuntimeError,msg);
    break;
  }
}

#define SWIG_exception(a,b) { _SWIG_exception(a,b); SWIG_fail; }


struct cb_handle {
	PyObject	*func;
	PyObject	*arg;
};


static char		_dnet_errmsg[256];
static int		_dnet_errcode = 0;

static void
dnet_error(int code, const char *fmt, ...)
{
	va_list ap;

	if (fmt != NULL) {
		va_start(ap, fmt);
		vsnprintf(_dnet_errmsg, sizeof(_dnet_errmsg), fmt, ap);
		va_end(ap);
	} else {
		strncpy(_dnet_errmsg, strerror(errno), 
		    sizeof(_dnet_errmsg) - 1);
		_dnet_errmsg[sizeof(_dnet_errmsg) - 1] = '\0';
	}
	_dnet_errcode = code;
}


/* Helper routines for addr_{eth,ip,ip6} members */
static PyObject *
__addr_data_get(struct addr *a, int type, int len)
 {
	if (a->addr_type != type) {
		dnet_error(SWIG_TypeError, "address type is %d", a->addr_type);
		return (NULL);
	}
	return (PyString_FromStringAndSize(a->addr_data8, len));
}

static void
__addr_data_set(struct addr *a, PyObject *obj, int len) 
{
	char *p;
	int n;
		if (PyArg_Parse(obj, "s#:addr_data_set", &p, &n) && n == len) {
		memcpy(a->addr_data8, p, len);
	} else
		dnet_error(SWIG_ValueError, "expected %d-byte binary string",
		    len);
}

static PyObject *addr_eth_get(struct addr *a) {
	return (__addr_data_get(a, ADDR_TYPE_ETH, ETH_ADDR_LEN));
}
static void addr_eth_set(struct addr *a, PyObject *obj) {
	__addr_data_set(a, obj, ETH_ADDR_LEN);
}
static PyObject *addr_ip_get(struct addr *a) {
	return (__addr_data_get(a, ADDR_TYPE_IP, IP_ADDR_LEN));
}
static void addr_ip_set(struct addr *a, PyObject *obj) {
	__addr_data_set(a, obj, IP_ADDR_LEN);
}
static PyObject *addr_ip6_get(struct addr *a) {
	return (__addr_data_get(a, ADDR_TYPE_IP6, IP6_ADDR_LEN));
}
static void addr_ip6_set(struct addr *a, PyObject *obj) {
	__addr_data_set(a, obj, IP6_ADDR_LEN);
}

/* Python iterator object for addr */
struct addr_iter {
	struct addr	cur;	/* XXX - in HBO */
	struct addr	max;	/* XXX - in HBO */
};

struct addr_iter *new_addr_iter(){
		return (calloc(1, sizeof(struct addr_iter)));
	}
void delete_addr_iter(struct addr_iter *self){
		free(self);
	}
struct addr_iter *addr_iter___iter__(struct addr_iter *self){
		return (self);
	}
struct addr *addr_iter_next(struct addr_iter *self){
		struct addr *a = NULL;
		
		/* XXX - only handle IPv4 for now */
		if (self->cur.addr_ip <= self->max.addr_ip) {
			a = malloc(sizeof(*a));
			memcpy(a, self, sizeof(*a));
			a->addr_ip = htonl(self->cur.addr_ip++);
		}		
                return (a);
	}
struct addr *new_addr__SWIG_0(){
		return ((struct addr *)calloc(1, sizeof(struct addr)));
	}
struct addr *new_addr__SWIG_1(char *addrtxt){
		struct addr *a = calloc(1, sizeof(*a));
		if (addr_aton(addrtxt, a) < 0) {
			free(a), a = NULL;
			dnet_error(SWIG_ValueError, NULL);
		}
		return (a);
	}
void delete_addr(struct addr *self){
		free(self);
	}
struct addr *addr___bcast(struct addr *self){
		struct addr *a = malloc(sizeof(*a));

		if (addr_bcast(self, a) < 0) {
			free(a), a = NULL;
			dnet_error(SWIG_RuntimeError, NULL);
		}
		return (a);
	}
struct addr *addr___net(struct addr *self){
		struct addr *a = malloc(sizeof(*a));

		if (addr_net(self, a) < 0) {
			free(a), a = NULL;
			dnet_error(SWIG_RuntimeError, NULL);
		}
		return (a);
	}
int addr___cmp__(struct addr *self,struct addr *other){
		return (other != NULL ? addr_cmp(self, other) : 1);
	}
int addr___contains__(struct addr *self,struct addr *other){
		struct addr s1, s2, o1, o2;

		if (addr_net(self, &s1) != 0 || addr_bcast(self, &s2) != 0 ||
		    addr_net(other, &o1) != 0 || addr_bcast(other, &o2) != 0)
			return (0);
		return (addr_cmp(&o1, &s1) >= 0 && addr_cmp(&o2, &s2) <= 0);
	}
struct addr_iter *addr___iter__(struct addr *self){
		struct addr_iter *ai = malloc(sizeof(*ai));
		
		/* XXX - only handle IPv4 for now */
		if (self->addr_type != 2 ||
		    addr_net(self, &ai->cur) < 0 || 
		    addr_bcast(self, &ai->max) < 0) {
			dnet_error(SWIG_ValueError, "expected IP address");
			free(ai), ai = NULL;
		} else {
			ai->cur.addr_ip = ntohl(ai->cur.addr_ip);
			ai->max.addr_ip = ntohl(ai->max.addr_ip);
		}
		return (ai);
	}
long addr___len__(struct addr *self){
		long len = 0;
		
		// XXX - only handle IPv4 now, also need to handle > MAXINT
		if (self->addr_type == 2) {
			len = pow(2, IP_ADDR_BITS - self->addr_bits);
		} else if (self->addr_type == 1 ||
		    self->addr_type == 3) {
			len = 1;
		}
		return (len);
	}
char *addr___str__(struct addr *self){
		return (addr_ntoa(self));
	}

void __eth_pack_hdr(char *eth_hdr,
	char *buf1, int len1, char *buf2, int len2, int type) {
	if (len1 == ETH_ADDR_LEN && len2 == ETH_ADDR_LEN) {
		eth_pack_hdr(eth_hdr, *buf1, *buf2, type);
	} else
		dnet_error(SWIG_ValueError, "invalid MAC addresses");
}
void __eth_aton(char *buf, char *eth_addr) {
	if (eth_aton(buf, (eth_addr_t *)eth_addr) < 0)
		dnet_error(SWIG_RuntimeError, NULL);
}
char *__eth_ntoa(char *buf1, int len1) {
	if (len1 != ETH_ADDR_LEN) {
		dnet_error(SWIG_ValueError, 
		    "expected 6-byte binary string");
		return (NULL);
	}
	return (eth_ntoa((eth_addr_t *)buf1));
}


static PyObject* t_output_helper(PyObject* target, PyObject* o) {
    PyObject*   o2;
    PyObject*   o3;

    if (!target) {                   
        target = o;
    } else if (target == Py_None) {  
        Py_DECREF(Py_None);
        target = o;
    } else {                         
        if (!PyTuple_Check(target)) {
            o2 = target;
            target = PyTuple_New(1);
            PyTuple_SetItem(target, 0, o2);
        }
        o3 = PyTuple_New(1);            
        PyTuple_SetItem(o3, 0, o);      

        o2 = target;
        target = PySequence_Concat(o2, o3); 
        Py_DECREF(o2);                      
        Py_DECREF(o3);
    }
    return target;
}

struct eth_handle *new_eth_handle(char *buf1,int len1){
		eth_t *eth = eth_open(buf1);
		if (eth == NULL)
			dnet_error(SWIG_RuntimeError, NULL);
		return (eth);
	}
void delete_eth_handle(struct eth_handle *self){
		eth_close(self);
	}
void eth_handle_get(struct eth_handle *self,char *eth_addr){
		if (eth_get(self, (eth_addr_t *)eth_addr) < 0)
			dnet_error(SWIG_RuntimeError, NULL);
	}
void eth_handle_set(struct eth_handle *self,char *buf1,int len1){
		if (len1 != 6) {
			dnet_error(SWIG_ValueError,
			    "expected a 6-byte binary string");
		} else if (eth_set(self, (eth_addr_t *)buf1) < 0)
			dnet_error(SWIG_RuntimeError, NULL);
	}
int eth_handle_send(struct eth_handle *self,char *buf1,int len1){
		return (eth_send(self, buf1, len1));
	}

void __icmp_pack_hdr(char *icmp_hdr, int type, int code) {
	icmp_pack_hdr(icmp_hdr, type, code);
}
void __icmp_pack_hdr_echo(char **dstp, int *dlenp, int type, int code,
	int id, int seq, char *buf1, int len1) {
	*dlenp = ICMP_LEN_MIN + len1;
        *dstp = calloc(1, *dlenp);
	icmp_pack_hdr_echo(*dstp, type, code, id, seq, buf1, len1);
}


void __ip_pack_hdr(char *ip_hdr,
	int tos, int len, int id, int off, int ttl, int p,
	char *buf1, int len1, char *buf2, int len2) {
	if (len1 == IP_ADDR_LEN && len2 == IP_ADDR_LEN)
		ip_pack_hdr(ip_hdr, tos, len, id, off, ttl, p, 
		    *(uint32_t *)buf1, *(uint32_t *)buf2);
}
void __ip_aton(char *buf, char *ip_addr) {
	ip_aton(buf, (ip_addr_t *)ip_addr);
}
char *__ip_ntoa(char *buf1, int len1) {
	if (len1 != IP_ADDR_LEN)
		return (NULL);
	return (ip_ntoa((ip_addr_t *)buf1));
}
void __ip_checksum(char **dstp, int *dlenp, char *src, int slen) {
	*dstp = malloc(slen); *dlenp = slen;
	memcpy(*dstp, src, *dlenp);
	ip_checksum(*dstp, *dlenp);
}

struct ip_handle *new_ip_handle(){
		ip_t *ip = ip_open();
		if (ip == NULL)
			dnet_error(SWIG_RuntimeError, NULL);
		return (ip);
	}
void delete_ip_handle(struct ip_handle *self){
		ip_close(self);
	}
int ip_handle_send(struct ip_handle *self,char *buf1,int len1){
		return (ip_send(self, buf1, len1));
	}
 
void __arp_pack_hdr_ethip(char *arp_ethip, int op,
        char *buf1, int len1, char *buf2, int len2,
        char *buf3, int len3, char *buf4, int len4) {
	if (len1 == ETH_ADDR_LEN && len2 == IP_ADDR_LEN &&
	    len3 == ETH_ADDR_LEN && len4 == IP_ADDR_LEN) {
		arp_pack_hdr_ethip(arp_ethip, op, *buf1, *buf2, *buf3, *buf4);
	} else
		dnet_error(SWIG_ValueError, "invalid argument lengths");
}

struct arp_handle *new_arp_handle(){
		arp_t *arp = arp_open();
		if (arp == NULL)
			dnet_error(SWIG_RuntimeError, NULL);
		return (arp);
	}
void delete_arp_handle(struct arp_handle *self){
		arp_close(self);
	}
void arp_handle_add(struct arp_handle *self,struct addr *pa,struct addr *ha){
		struct arp_entry entry;

		memcpy(&entry.arp_pa, pa, sizeof(*pa));
		memcpy(&entry.arp_ha, ha, sizeof(*ha));
		if (arp_add(self, &entry) < 0)
			dnet_error(SWIG_RuntimeError, NULL);
	}
void arp_handle_delete(struct arp_handle *self,struct addr *pa){
		struct arp_entry entry;

		memset(&entry, 0, sizeof(entry));
		memcpy(&entry.arp_pa, pa, sizeof(*pa));
		if (arp_delete(self, &entry) < 0)
			dnet_error(SWIG_RuntimeError, NULL);
	}
struct addr *arp_handle_get(struct arp_handle *self,struct addr *pa){
		struct arp_entry entry;
		struct addr *ha = NULL;

		memcpy(&entry.arp_pa, pa, sizeof(*pa));
		if (arp_get(self, &entry) == 0) {
			ha = calloc(1, sizeof(*ha));
			memcpy(ha, &entry.arp_ha, sizeof(*ha));
		} else {
			dnet_error(SWIG_RuntimeError, NULL);
		}
		return (ha);
	}

	int __arp_loop_cb(const struct arp_entry *entry, void *arg) {
		struct cb_handle *cb = (struct cb_handle *)arg;
		PyObject *arglist, *result = NULL;
	
		if (PyCallable_Check(cb->func)) {
			arglist = Py_BuildValue("OOO", 
			    SWIG_NewPointerObj((void *)&entry->arp_pa, 
			    SWIGTYPE_p_addr, 1),
			    SWIG_NewPointerObj((void *)&entry->arp_ha,
			    SWIGTYPE_p_addr, 1), cb->arg);
			result = PyObject_CallObject(cb->func, arglist);
			Py_DECREF(arglist);
			Py_XDECREF(result);	
		}
		return (result == NULL ? -1 : 0);
	}

void arp_handle_loop(struct arp_handle *self,PyObject *callback,PyObject *arg){
		struct cb_handle cb;

		cb.func = callback;
		cb.arg = arg;
		arp_loop(self, __arp_loop_cb, &cb);
	}
struct rand_handle *new_rand_handle(){
		return (rand_open());
	}
void delete_rand_handle(struct rand_handle *self){
		rand_close(self);
	}
void rand_handle_get(struct rand_handle *self,char **dstp,int *dlenp,int len){
		*dstp = malloc(len); *dlenp = len;
		if (rand_get(self, *dstp, *dlenp) < 0)
			dnet_error(SWIG_RuntimeError, NULL);
	}
void rand_handle_set(struct rand_handle *self,char *buf1,int len1){
		if (rand_set(self, buf1, len1) < 0)
			dnet_error(SWIG_RuntimeError, NULL);
	}
void rand_handle_add(struct rand_handle *self,char *buf1,int len1){
		if (rand_add(self, buf1, len1) < 0)
			dnet_error(SWIG_RuntimeError, NULL);
	}
unsigned char rand_handle_uint8(struct rand_handle *self){
		return (rand_uint8(self));
	}
unsigned short rand_handle_uint16(struct rand_handle *self){
		return (rand_uint16(self));
	}
unsigned int rand_handle_uint32(struct rand_handle *self){
		return (rand_uint32(self));
	}
struct route_handle *new_route_handle(){
		route_t *r = route_open();
		if (r == NULL)
			dnet_error(SWIG_RuntimeError, NULL);
		return (r);
	}
void delete_route_handle(struct route_handle *self){
		route_close(self);
	}
int route_handle_add(struct route_handle *self,struct addr *dst,struct addr *gw){
		struct route_entry entry;

		memcpy(&entry.route_dst, dst, sizeof(*dst));
		memcpy(&entry.route_gw, gw, sizeof(*gw));
		return (route_add(self, &entry));
	}
int route_handle_delete(struct route_handle *self,struct addr *dst){
		struct route_entry entry;

		memset(&entry, 0, sizeof(entry));
		memcpy(&entry.route_dst, dst, sizeof(*dst));
		return (route_delete(self, &entry));
	}
struct addr *route_handle_get(struct route_handle *self,struct addr *dst){
		struct route_entry entry;
		struct addr *gw = NULL;

		memcpy(&entry.route_dst, dst, sizeof(*dst));
		if (route_get(self, &entry) == 0) {
			gw = calloc(1, sizeof(*gw));
			memcpy(gw, &entry.route_gw, sizeof(*gw));
		}
		return (gw);
	}

	int __route_loop_cb(const struct route_entry *entry, void *arg) {
		struct cb_handle *cb = (struct cb_handle *)arg;
		PyObject *arglist, *result = NULL;
		
		if (PyCallable_Check(cb->func)) {
			arglist = Py_BuildValue("OOO", 
			    SWIG_NewPointerObj((void *)&entry->route_dst, 
			    SWIGTYPE_p_addr, 1),
			    SWIG_NewPointerObj((void *)&entry->route_gw,
			    SWIGTYPE_p_addr, 1), cb->arg);
			result = PyObject_CallObject(cb->func, arglist);
			Py_DECREF(arglist);
			Py_XDECREF(result);
		}
		return (result == NULL ? -1 : 0);
	}

void route_handle_loop(struct route_handle *self,PyObject *callback,PyObject *arg){
		struct cb_handle cb;

		cb.func = callback;
		cb.arg = arg;
		route_loop(self, __route_loop_cb, &cb);
	}
#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_new_addr_iter(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr_iter *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_addr_iter")) goto fail;
    {
        result = (struct addr_iter *)new_addr_iter();
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_addr_iter, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_addr_iter(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr_iter *arg1 = (struct addr_iter *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_addr_iter",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr_iter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        delete_addr_iter(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr_iter___iter__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr_iter *arg1 = (struct addr_iter *) 0 ;
    struct addr_iter *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:addr_iter___iter__",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr_iter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (struct addr_iter *)addr_iter___iter__(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_addr_iter, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr_iter_next(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr_iter *arg1 = (struct addr_iter *) 0 ;
    struct addr *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:addr_iter_next",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr_iter,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (struct addr *)addr_iter_next(arg1);
        
        if (!result) {
            PyErr_SetNone(PyExc_StopIteration);
            return (NULL);
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_addr, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject * addr_iter_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_addr_iter, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_addr_type_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    uint16_t arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:addr_type_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg2 = (uint16_t) PyInt_AsLong(obj1);
    if (PyErr_Occurred()) SWIG_fail;
    if (arg1) (arg1)->addr_type = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr_type_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    uint16_t result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:addr_type_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (uint16_t) ((arg1)->addr_type);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr_bits_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    uint16_t arg2 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:addr_bits_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg2 = (uint16_t) PyInt_AsLong(obj1);
    if (PyErr_Occurred()) SWIG_fail;
    if (arg1) (arg1)->addr_bits = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr_bits_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    uint16_t result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:addr_bits_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (uint16_t) ((arg1)->addr_bits);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr_eth_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    PyObject *arg2 = (PyObject *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:addr_eth_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg2 = obj1;
    {
        addr_eth_set(arg1,arg2);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr_eth_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    PyObject *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:addr_eth_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (PyObject *)addr_eth_get(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = result;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr_ip_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    PyObject *arg2 = (PyObject *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:addr_ip_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg2 = obj1;
    {
        addr_ip_set(arg1,arg2);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr_ip_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    PyObject *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:addr_ip_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (PyObject *)addr_ip_get(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = result;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr_ip6_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    PyObject *arg2 = (PyObject *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:addr_ip6_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg2 = obj1;
    {
        addr_ip6_set(arg1,arg2);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr_ip6_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    PyObject *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:addr_ip6_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (PyObject *)addr_ip6_get(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = result;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_addr__SWIG_0(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_addr")) goto fail;
    {
        result = (struct addr *)new_addr__SWIG_0();
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_addr, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_addr__SWIG_1(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    struct addr *result;
    
    if(!PyArg_ParseTuple(args,(char *)"s:new_addr",&arg1)) goto fail;
    {
        result = (struct addr *)new_addr__SWIG_1(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_addr, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_addr(PyObject *self, PyObject *args) {
    int argc;
    PyObject *argv[2];
    int ii;
    
    argc = PyObject_Length(args);
    for (ii = 0; (ii < argc) && (ii < 1); ii++) {
        argv[ii] = PyTuple_GetItem(args,ii);
    }
    if (argc == 0) {
        return _wrap_new_addr__SWIG_0(self,args);
    }
    if (argc == 1) {
        int _v;
        {
            _v = PyString_Check(argv[0]) ? 1 : 0;
        }
        if (_v) {
            return _wrap_new_addr__SWIG_1(self,args);
        }
    }
    
    PyErr_SetString(PyExc_TypeError,"No matching function for overloaded 'new_addr'");
    return NULL;
}


static PyObject *_wrap_delete_addr(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_addr",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        delete_addr(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr_bcast(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    struct addr *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:addr_bcast",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (struct addr *)addr___bcast(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_addr, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr_net(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    struct addr *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:addr_net",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (struct addr *)addr___net(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_addr, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr___cmp__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    struct addr *arg2 = (struct addr *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:addr___cmp__",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (int)addr___cmp__(arg1,arg2);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr___contains__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    struct addr *arg2 = (struct addr *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:addr___contains__",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (int)addr___contains__(arg1,arg2);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr___iter__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    struct addr_iter *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:addr___iter__",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (struct addr_iter *)addr___iter__(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_addr_iter, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr___len__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    long result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:addr___len__",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (long)addr___len__(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_addr___str__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct addr *arg1 = (struct addr *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:addr___str__",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (char *)addr___str__(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject * addr_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_addr, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap___eth_pack_hdr(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    char *arg2 ;
    int arg3 ;
    char *arg4 ;
    int arg5 ;
    int arg6 ;
    char temp1[14] ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    {
        arg1 = (char *) temp1;
    }
    if(!PyArg_ParseTuple(args,(char *)"OOi:__eth_pack_hdr",&obj0,&obj1,&arg6)) goto fail;
    {
        arg2 = (char *) PyString_AsString(obj0);
        arg3 = (int) PyString_Size(obj0);
    }
    {
        arg4 = (char *) PyString_AsString(obj1);
        arg5 = (int) PyString_Size(obj1);
    }
    {
        __eth_pack_hdr(arg1,arg2,arg3,arg4,arg5,arg6);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        PyObject *o = PyString_FromStringAndSize(arg1,14);
        resultobj = t_output_helper(resultobj,o);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap___eth_aton(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    char *arg2 ;
    char temp2[6] ;
    
    {
        arg2 = (char *) temp2;
    }
    if(!PyArg_ParseTuple(args,(char *)"s:__eth_aton",&arg1)) goto fail;
    {
        __eth_aton(arg1,arg2);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        PyObject *o = PyString_FromStringAndSize(arg2,6);
        resultobj = t_output_helper(resultobj,o);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap___eth_ntoa(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    int arg2 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:__eth_ntoa",&obj0)) goto fail;
    {
        arg1 = (char *) PyString_AsString(obj0);
        arg2 = (int) PyString_Size(obj0);
    }
    {
        result = (char *)__eth_ntoa(arg1,arg2);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_eth(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    int arg2 ;
    struct eth_handle *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:new_eth",&obj0)) goto fail;
    {
        arg1 = (char *) PyString_AsString(obj0);
        arg2 = (int) PyString_Size(obj0);
    }
    {
        result = (struct eth_handle *)new_eth_handle(arg1,arg2);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_eth_handle, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_eth(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct eth_handle *arg1 = (struct eth_handle *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_eth",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_eth_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        delete_eth_handle(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_eth_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct eth_handle *arg1 = (struct eth_handle *) 0 ;
    char *arg2 ;
    char temp2[6] ;
    PyObject * obj0 = 0 ;
    
    {
        arg2 = (char *) temp2;
    }
    if(!PyArg_ParseTuple(args,(char *)"O:eth_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_eth_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        eth_handle_get(arg1,arg2);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        PyObject *o = PyString_FromStringAndSize(arg2,6);
        resultobj = t_output_helper(resultobj,o);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_eth_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct eth_handle *arg1 = (struct eth_handle *) 0 ;
    char *arg2 ;
    int arg3 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:eth_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_eth_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        arg2 = (char *) PyString_AsString(obj1);
        arg3 = (int) PyString_Size(obj1);
    }
    {
        eth_handle_set(arg1,arg2,arg3);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_eth_send(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct eth_handle *arg1 = (struct eth_handle *) 0 ;
    char *arg2 ;
    int arg3 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:eth_send",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_eth_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        arg2 = (char *) PyString_AsString(obj1);
        arg3 = (int) PyString_Size(obj1);
    }
    {
        result = (int)eth_handle_send(arg1,arg2,arg3);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject * eth_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_eth_handle, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap___icmp_pack_hdr(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    int arg2 ;
    int arg3 ;
    char temp1[ICMP_HDR_LEN] ;
    
    {
        arg1 = (char *) temp1;
    }
    if(!PyArg_ParseTuple(args,(char *)"ii:__icmp_pack_hdr",&arg2,&arg3)) goto fail;
    {
        __icmp_pack_hdr(arg1,arg2,arg3);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        PyObject *o = PyString_FromStringAndSize(arg1,ICMP_HDR_LEN);
        resultobj = t_output_helper(resultobj,o);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap___icmp_pack_hdr_echo(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char **arg1 = (char **) 0 ;
    int *arg2 = (int *) 0 ;
    int arg3 ;
    int arg4 ;
    int arg5 ;
    int arg6 ;
    char *arg7 ;
    int arg8 ;
    char *temp1 = 0 ;
    int tempn1 ;
    PyObject * obj4 = 0 ;
    
    {
        arg1 = &temp1;
        arg2 = &tempn1;
    }
    if(!PyArg_ParseTuple(args,(char *)"iiiiO:__icmp_pack_hdr_echo",&arg3,&arg4,&arg5,&arg6,&obj4)) goto fail;
    {
        arg7 = (char *) PyString_AsString(obj4);
        arg8 = (int) PyString_Size(obj4);
    }
    {
        __icmp_pack_hdr_echo(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        if (*arg1) {
            PyObject *o = PyString_FromStringAndSize(*arg1,*arg2);
            free(*arg1);
            resultobj = t_output_helper(resultobj,o);
        }
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap___ip_pack_hdr(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    int arg2 ;
    int arg3 ;
    int arg4 ;
    int arg5 ;
    int arg6 ;
    int arg7 ;
    char *arg8 ;
    int arg9 ;
    char *arg10 ;
    int arg11 ;
    char temp1[20] ;
    PyObject * obj6 = 0 ;
    PyObject * obj7 = 0 ;
    
    {
        arg1 = (char *) temp1;
    }
    if(!PyArg_ParseTuple(args,(char *)"iiiiiiOO:__ip_pack_hdr",&arg2,&arg3,&arg4,&arg5,&arg6,&arg7,&obj6,&obj7)) goto fail;
    {
        arg8 = (char *) PyString_AsString(obj6);
        arg9 = (int) PyString_Size(obj6);
    }
    {
        arg10 = (char *) PyString_AsString(obj7);
        arg11 = (int) PyString_Size(obj7);
    }
    {
        __ip_pack_hdr(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        PyObject *o = PyString_FromStringAndSize(arg1,20);
        resultobj = t_output_helper(resultobj,o);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap___ip_aton(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    char *arg2 ;
    char temp2[4] ;
    
    {
        arg2 = (char *) temp2;
    }
    if(!PyArg_ParseTuple(args,(char *)"s:__ip_aton",&arg1)) goto fail;
    {
        __ip_aton(arg1,arg2);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        PyObject *o = PyString_FromStringAndSize(arg2,4);
        resultobj = t_output_helper(resultobj,o);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap___ip_ntoa(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    int arg2 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:__ip_ntoa",&obj0)) goto fail;
    {
        arg1 = (char *) PyString_AsString(obj0);
        arg2 = (int) PyString_Size(obj0);
    }
    {
        result = (char *)__ip_ntoa(arg1,arg2);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap___ip_checksum(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char **arg1 = (char **) 0 ;
    int *arg2 = (int *) 0 ;
    char *arg3 ;
    int arg4 ;
    char *temp1 = 0 ;
    int tempn1 ;
    
    {
        arg1 = &temp1;
        arg2 = &tempn1;
    }
    if(!PyArg_ParseTuple(args,(char *)"si:__ip_checksum",&arg3,&arg4)) goto fail;
    {
        __ip_checksum(arg1,arg2,arg3,arg4);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        if (*arg1) {
            PyObject *o = PyString_FromStringAndSize(*arg1,*arg2);
            free(*arg1);
            resultobj = t_output_helper(resultobj,o);
        }
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_ip(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct ip_handle *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_ip")) goto fail;
    {
        result = (struct ip_handle *)new_ip_handle();
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_ip_handle, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_ip(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct ip_handle *arg1 = (struct ip_handle *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_ip",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_ip_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        delete_ip_handle(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_ip_send(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct ip_handle *arg1 = (struct ip_handle *) 0 ;
    char *arg2 ;
    int arg3 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:ip_send",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_ip_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        arg2 = (char *) PyString_AsString(obj1);
        arg3 = (int) PyString_Size(obj1);
    }
    {
        result = (int)ip_handle_send(arg1,arg2,arg3);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject * ip_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_ip_handle, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap___arp_pack_hdr_ethip(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    int arg2 ;
    char *arg3 ;
    int arg4 ;
    char *arg5 ;
    int arg6 ;
    char *arg7 ;
    int arg8 ;
    char *arg9 ;
    int arg10 ;
    char temp1[8+20] ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    PyObject * obj3 = 0 ;
    PyObject * obj4 = 0 ;
    
    {
        arg1 = (char *) temp1;
    }
    if(!PyArg_ParseTuple(args,(char *)"iOOOO:__arp_pack_hdr_ethip",&arg2,&obj1,&obj2,&obj3,&obj4)) goto fail;
    {
        arg3 = (char *) PyString_AsString(obj1);
        arg4 = (int) PyString_Size(obj1);
    }
    {
        arg5 = (char *) PyString_AsString(obj2);
        arg6 = (int) PyString_Size(obj2);
    }
    {
        arg7 = (char *) PyString_AsString(obj3);
        arg8 = (int) PyString_Size(obj3);
    }
    {
        arg9 = (char *) PyString_AsString(obj4);
        arg10 = (int) PyString_Size(obj4);
    }
    {
        __arp_pack_hdr_ethip(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        PyObject *o = PyString_FromStringAndSize(arg1,8 + 20);
        resultobj = t_output_helper(resultobj,o);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_new_arp(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct arp_handle *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_arp")) goto fail;
    {
        result = (struct arp_handle *)new_arp_handle();
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_arp_handle, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_arp(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct arp_handle *arg1 = (struct arp_handle *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_arp",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_arp_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        delete_arp_handle(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_arp_add(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct arp_handle *arg1 = (struct arp_handle *) 0 ;
    struct addr *arg2 = (struct addr *) 0 ;
    struct addr *arg3 = (struct addr *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:arp_add",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_arp_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        arp_handle_add(arg1,arg2,arg3);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_arp_delete(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct arp_handle *arg1 = (struct arp_handle *) 0 ;
    struct addr *arg2 = (struct addr *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:arp_delete",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_arp_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        arp_handle_delete(arg1,arg2);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_arp_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct arp_handle *arg1 = (struct arp_handle *) 0 ;
    struct addr *arg2 = (struct addr *) 0 ;
    struct addr *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:arp_get",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_arp_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (struct addr *)arp_handle_get(arg1,arg2);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_addr, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_arp_loop(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct arp_handle *arg1 = (struct arp_handle *) 0 ;
    PyObject *arg2 = (PyObject *) 0 ;
    PyObject *arg3 = (PyObject *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:arp_loop",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_arp_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg2 = obj1;
    arg3 = obj2;
    {
        arp_handle_loop(arg1,arg2,arg3);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject * arp_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_arp_handle, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_new_rand(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct rand_handle *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_rand")) goto fail;
    {
        result = (struct rand_handle *)new_rand_handle();
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_rand_handle, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_rand(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct rand_handle *arg1 = (struct rand_handle *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_rand",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_rand_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        delete_rand_handle(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_rand_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct rand_handle *arg1 = (struct rand_handle *) 0 ;
    char **arg2 = (char **) 0 ;
    int *arg3 = (int *) 0 ;
    int arg4 ;
    char *temp2 = 0 ;
    int tempn2 ;
    PyObject * obj0 = 0 ;
    
    {
        arg2 = &temp2;
        arg3 = &tempn2;
    }
    if(!PyArg_ParseTuple(args,(char *)"Oi:rand_get",&obj0,&arg4)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_rand_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        rand_handle_get(arg1,arg2,arg3,arg4);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    {
        if (*arg2) {
            PyObject *o = PyString_FromStringAndSize(*arg2,*arg3);
            free(*arg2);
            resultobj = t_output_helper(resultobj,o);
        }
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_rand_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct rand_handle *arg1 = (struct rand_handle *) 0 ;
    char *arg2 ;
    int arg3 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:rand_set",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_rand_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        arg2 = (char *) PyString_AsString(obj1);
        arg3 = (int) PyString_Size(obj1);
    }
    {
        rand_handle_set(arg1,arg2,arg3);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_rand_add(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct rand_handle *arg1 = (struct rand_handle *) 0 ;
    char *arg2 ;
    int arg3 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:rand_add",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_rand_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        arg2 = (char *) PyString_AsString(obj1);
        arg3 = (int) PyString_Size(obj1);
    }
    {
        rand_handle_add(arg1,arg2,arg3);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_rand_uint8(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct rand_handle *arg1 = (struct rand_handle *) 0 ;
    unsigned char result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:rand_uint8",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_rand_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (unsigned char)rand_handle_uint8(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_rand_uint16(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct rand_handle *arg1 = (struct rand_handle *) 0 ;
    unsigned short result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:rand_uint16",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_rand_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (unsigned short)rand_handle_uint16(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_rand_uint32(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct rand_handle *arg1 = (struct rand_handle *) 0 ;
    unsigned int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:rand_uint32",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_rand_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (unsigned int)rand_handle_uint32(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject * rand_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_rand_handle, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_new_route(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct route_handle *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_route")) goto fail;
    {
        result = (struct route_handle *)new_route_handle();
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_route_handle, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_delete_route(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct route_handle *arg1 = (struct route_handle *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_route",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_route_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        delete_route_handle(arg1);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_route_add(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct route_handle *arg1 = (struct route_handle *) 0 ;
    struct addr *arg2 = (struct addr *) 0 ;
    struct addr *arg3 = (struct addr *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:route_add",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_route_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (int)route_handle_add(arg1,arg2,arg3);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_route_delete(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct route_handle *arg1 = (struct route_handle *) 0 ;
    struct addr *arg2 = (struct addr *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:route_delete",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_route_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (int)route_handle_delete(arg1,arg2);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_route_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct route_handle *arg1 = (struct route_handle *) 0 ;
    struct addr *arg2 = (struct addr *) 0 ;
    struct addr *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:route_get",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_route_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_addr,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    {
        result = (struct addr *)route_handle_get(arg1,arg2);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_addr, 1);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_route_loop(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    struct route_handle *arg1 = (struct route_handle *) 0 ;
    PyObject *arg2 = (PyObject *) 0 ;
    PyObject *arg3 = (PyObject *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:route_loop",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_route_handle,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg2 = obj1;
    arg3 = obj2;
    {
        route_handle_loop(arg1,arg2,arg3);
        
        if (_dnet_errcode != 0) {
            int code = _dnet_errcode;
            _dnet_errcode = 0;
            SWIG_exception(code, _dnet_errmsg);
        }
    }
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject * route_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_route_handle, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyMethodDef SwigMethods[] = {
	 { (char *)"new_addr_iter", _wrap_new_addr_iter, METH_VARARGS },
	 { (char *)"delete_addr_iter", _wrap_delete_addr_iter, METH_VARARGS },
	 { (char *)"addr_iter___iter__", _wrap_addr_iter___iter__, METH_VARARGS },
	 { (char *)"addr_iter_next", _wrap_addr_iter_next, METH_VARARGS },
	 { (char *)"addr_iter_swigregister", addr_iter_swigregister, METH_VARARGS },
	 { (char *)"addr_type_set", _wrap_addr_type_set, METH_VARARGS },
	 { (char *)"addr_type_get", _wrap_addr_type_get, METH_VARARGS },
	 { (char *)"addr_bits_set", _wrap_addr_bits_set, METH_VARARGS },
	 { (char *)"addr_bits_get", _wrap_addr_bits_get, METH_VARARGS },
	 { (char *)"addr_eth_set", _wrap_addr_eth_set, METH_VARARGS },
	 { (char *)"addr_eth_get", _wrap_addr_eth_get, METH_VARARGS },
	 { (char *)"addr_ip_set", _wrap_addr_ip_set, METH_VARARGS },
	 { (char *)"addr_ip_get", _wrap_addr_ip_get, METH_VARARGS },
	 { (char *)"addr_ip6_set", _wrap_addr_ip6_set, METH_VARARGS },
	 { (char *)"addr_ip6_get", _wrap_addr_ip6_get, METH_VARARGS },
	 { (char *)"new_addr", _wrap_new_addr, METH_VARARGS },
	 { (char *)"delete_addr", _wrap_delete_addr, METH_VARARGS },
	 { (char *)"addr_bcast", _wrap_addr_bcast, METH_VARARGS },
	 { (char *)"addr_net", _wrap_addr_net, METH_VARARGS },
	 { (char *)"addr___cmp__", _wrap_addr___cmp__, METH_VARARGS },
	 { (char *)"addr___contains__", _wrap_addr___contains__, METH_VARARGS },
	 { (char *)"addr___iter__", _wrap_addr___iter__, METH_VARARGS },
	 { (char *)"addr___len__", _wrap_addr___len__, METH_VARARGS },
	 { (char *)"addr___str__", _wrap_addr___str__, METH_VARARGS },
	 { (char *)"addr_swigregister", addr_swigregister, METH_VARARGS },
	 { (char *)"__eth_pack_hdr", _wrap___eth_pack_hdr, METH_VARARGS },
	 { (char *)"__eth_aton", _wrap___eth_aton, METH_VARARGS },
	 { (char *)"__eth_ntoa", _wrap___eth_ntoa, METH_VARARGS },
	 { (char *)"new_eth", _wrap_new_eth, METH_VARARGS },
	 { (char *)"delete_eth", _wrap_delete_eth, METH_VARARGS },
	 { (char *)"eth_get", _wrap_eth_get, METH_VARARGS },
	 { (char *)"eth_set", _wrap_eth_set, METH_VARARGS },
	 { (char *)"eth_send", _wrap_eth_send, METH_VARARGS },
	 { (char *)"eth_swigregister", eth_swigregister, METH_VARARGS },
	 { (char *)"__icmp_pack_hdr", _wrap___icmp_pack_hdr, METH_VARARGS },
	 { (char *)"__icmp_pack_hdr_echo", _wrap___icmp_pack_hdr_echo, METH_VARARGS },
	 { (char *)"__ip_pack_hdr", _wrap___ip_pack_hdr, METH_VARARGS },
	 { (char *)"__ip_aton", _wrap___ip_aton, METH_VARARGS },
	 { (char *)"__ip_ntoa", _wrap___ip_ntoa, METH_VARARGS },
	 { (char *)"__ip_checksum", _wrap___ip_checksum, METH_VARARGS },
	 { (char *)"new_ip", _wrap_new_ip, METH_VARARGS },
	 { (char *)"delete_ip", _wrap_delete_ip, METH_VARARGS },
	 { (char *)"ip_send", _wrap_ip_send, METH_VARARGS },
	 { (char *)"ip_swigregister", ip_swigregister, METH_VARARGS },
	 { (char *)"__arp_pack_hdr_ethip", _wrap___arp_pack_hdr_ethip, METH_VARARGS },
	 { (char *)"new_arp", _wrap_new_arp, METH_VARARGS },
	 { (char *)"delete_arp", _wrap_delete_arp, METH_VARARGS },
	 { (char *)"arp_add", _wrap_arp_add, METH_VARARGS },
	 { (char *)"arp_delete", _wrap_arp_delete, METH_VARARGS },
	 { (char *)"arp_get", _wrap_arp_get, METH_VARARGS },
	 { (char *)"arp_loop", _wrap_arp_loop, METH_VARARGS },
	 { (char *)"arp_swigregister", arp_swigregister, METH_VARARGS },
	 { (char *)"new_rand", _wrap_new_rand, METH_VARARGS },
	 { (char *)"delete_rand", _wrap_delete_rand, METH_VARARGS },
	 { (char *)"rand_get", _wrap_rand_get, METH_VARARGS },
	 { (char *)"rand_set", _wrap_rand_set, METH_VARARGS },
	 { (char *)"rand_add", _wrap_rand_add, METH_VARARGS },
	 { (char *)"rand_uint8", _wrap_rand_uint8, METH_VARARGS },
	 { (char *)"rand_uint16", _wrap_rand_uint16, METH_VARARGS },
	 { (char *)"rand_uint32", _wrap_rand_uint32, METH_VARARGS },
	 { (char *)"rand_swigregister", rand_swigregister, METH_VARARGS },
	 { (char *)"new_route", _wrap_new_route, METH_VARARGS },
	 { (char *)"delete_route", _wrap_delete_route, METH_VARARGS },
	 { (char *)"route_add", _wrap_route_add, METH_VARARGS },
	 { (char *)"route_delete", _wrap_route_delete, METH_VARARGS },
	 { (char *)"route_get", _wrap_route_get, METH_VARARGS },
	 { (char *)"route_loop", _wrap_route_loop, METH_VARARGS },
	 { (char *)"route_swigregister", route_swigregister, METH_VARARGS },
	 { NULL, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_eth_handle[] = {{"_p_eth_handle", 0, "eth_handle *", 0},{"_p_eth_handle"},{0}};
static swig_type_info _swigt__p_ip_handle[] = {{"_p_ip_handle", 0, "ip_handle *", 0},{"_p_ip_handle"},{0}};
static swig_type_info _swigt__p_arp_handle[] = {{"_p_arp_handle", 0, "arp_handle *", 0},{"_p_arp_handle"},{0}};
static swig_type_info _swigt__p_rand_handle[] = {{"_p_rand_handle", 0, "rand_handle *", 0},{"_p_rand_handle"},{0}};
static swig_type_info _swigt__p_route_handle[] = {{"_p_route_handle", 0, "route_handle *", 0},{"_p_route_handle"},{0}};
static swig_type_info _swigt__p_p_char[] = {{"_p_p_char", 0, "char **", 0},{"_p_p_char"},{0}};
static swig_type_info _swigt__p_addr_iter[] = {{"_p_addr_iter", 0, "struct addr_iter *", 0},{"_p_addr_iter"},{0}};
static swig_type_info _swigt__p_addr[] = {{"_p_addr", 0, "struct addr *", 0},{"_p_addr"},{0}};
static swig_type_info _swigt__p_int[] = {{"_p_int", 0, "int *", 0},{"_p_int"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_eth_handle, 
_swigt__p_ip_handle, 
_swigt__p_arp_handle, 
_swigt__p_rand_handle, 
_swigt__p_route_handle, 
_swigt__p_p_char, 
_swigt__p_addr_iter, 
_swigt__p_addr, 
_swigt__p_int, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{ SWIG_PY_INT,     (char *)"ADDR_TYPE_NONE", (long) 0, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ADDR_TYPE_ETH", (long) 1, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ADDR_TYPE_IP", (long) 2, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ADDR_TYPE_IP6", (long) 3, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ETH_ADDR_LEN", (long) 6, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ETH_ADDR_BITS", (long) 48, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ETH_CRC_LEN", (long) 4, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ETH_HDR_LEN", (long) 14, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ETH_LEN_MIN", (long) 64, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ETH_LEN_MAX", (long) 1518, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ETH_MTU", (long) (1518-14-4), 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ETH_MIN", (long) (64-14-4), 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ETH_TYPE_IP", (long) 0x0800, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ETH_TYPE_ARP", (long) 0x0806, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ETH_TYPE_IPV6", (long) 0x86DD, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_ADDR_LEN", (long) 4, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_ADDR_BITS", (long) 32, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_HDR_LEN", (long) 20, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_OPT_LEN", (long) 2, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_OPT_LEN_MAX", (long) 40, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_HDR_LEN_MAX", (long) (20+40), 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_LEN_MAX", (long) 65535, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_LEN_MIN", (long) 20, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_RF", (long) 0x8000, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_DF", (long) 0x4000, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_MF", (long) 0x2000, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_OFFMASK", (long) 0x1fff, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_TTL_DEFAULT", (long) 64, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_TTL_MAX", (long) 255, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_PROTO_IP", (long) 0, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_PROTO_ICMP", (long) 1, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_PROTO_IGMP", (long) 2, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_PROTO_TCP", (long) 6, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_PROTO_UDP", (long) 17, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_PROTO_IPV6", (long) 41, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_PROTO_ROUTING", (long) 43, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_PROTO_FRAGMENT", (long) 44, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_PROTO_ICMPV6", (long) 58, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_PROTO_NONE", (long) 59, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_PROTO_DSTOPTS", (long) 60, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_PROTO_RAW", (long) 255, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_PROTO_RESERVED", (long) 255, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"IP_PROTO_MAX", (long) 255, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ARP_HDR_LEN", (long) 8, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ARP_ETHIP_LEN", (long) 20, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ARP_HRD_ETH", (long) 0x0001, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ARP_HRD_IEEE802", (long) 0x0006, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ARP_PRO_IP", (long) 0x0800, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ARP_OP_REQUEST", (long) 1, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ARP_OP_REPLY", (long) 2, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ARP_OP_REVREQUEST", (long) 3, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ARP_OP_REVREPLY", (long) 4, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"TCP_HDR_LEN", (long) 20, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"TH_FIN", (long) 0x01, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"TH_SYN", (long) 0x02, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"TH_RST", (long) 0x04, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"TH_PUSH", (long) 0x08, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"TH_ACK", (long) 0x10, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"TH_URG", (long) 0x20, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"TH_ECE", (long) 0x40, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"TH_CWR", (long) 0x80, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"TCP_PORT_MAX", (long) 65535, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"TCP_WIN_MAX", (long) 65535, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"UDP_HDR_LEN", (long) 8, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"UDP_PORT_MAX", (long) 65535, 0, 0, 0},
{0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0; 
    static int       typeinit = 0;
    PyObject *m, *d;
    int       i;
    if (!SWIG_globals) SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    if (!typeinit) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        typeinit = 1;
    }
    SWIG_InstallConstants(d,swig_const_table);
    
}

